### PR TITLE
Create pokemon.tw.json

### PR DESCRIPTION
**Pull request by lynch2032**

### CODE REVIEW

**Comment by niicojs** [comment]
Thanks. What is tw?

**Comment by lynch2032** [comment]
Taiwan.
Should i use zh_tw?

**Comment by niicojs** [comment]
No that's good.

**Comment by niicojs** [comment]
Could you translate inventory also? If not, I'll keep the english one as Taiwan.

**Comment by lynch2032** [comment]
OK. I'll do it later.

**Pull request merged**
