### PR TITLE
UI polish, possible candy labels 

### PR DESCRIPTION
**Pull request by Epinikion**
UI tweaks, probably show candy with next version, toolbar improvements
_needed to comment 2 lines candy stuff in socket.js to compile_

just in case you like it :)

necrovisualizer

necrovisualizer2

### CODE REVIEW

**Comment by Epinikion** [comment]
what a mess with those silly commits, sorry for that

**Comment by draggehn** [comment]
(For the future, you typically want to checkout a new branch (eg /feature_description) so any changes you make to your master doesn't conflict.)

Otherwise, I do think the changes look nice. Good work.

**Comment by niicojs** [comment]
to do clean PR:
- update fork from upstream
- rebase
- create branch
- switch to branch
- do some code
- PR

**Comment by niicojs** [comment]
I'm currently testing, look sgood :)
could you put some more contrast in the "waiting" screen?

**Comment by niicojs** [comment]
also, I don't really like the bounce in the toolbar

**Comment by niicojs** [comment]
also, when displaying the map I prefer the black border instead of the green, maybe we can keep it also

**Comment by niicojs** [comment]
I did some tweaks, I think I like it.
Toolbar is more like standard leaflet toolbar (non bounce or black color).
I have my black pading back :)
Sort hover is lighter than selected.

Thanks a lot, keep up :)

**Comment by Epinikion** [comment]
Thx, im not that git-expert. :)
Glad u liked it, will have a look on what u did right now. I love this Project!

**Pull request merged**
