### PR TITLE
ADD border color for possible evolve pokemon

### PR DESCRIPTION
**Pull request by deathart**

### CODE REVIEW

**Comment by deathart** [comment]
sans titre

**Comment by niicojs** [comment]
I like the idea of identifying pokemon that can evolve, but to be fair I don"'t really like the proposal.
I'm really not good at beautiful design,  maybe @Epinikion has an idea.

**Comment by deathart** [comment]
Oui mais en attendant de trouver plus beau :p c'est juste que je galèrer je les fait pour moi mais aprés j'ai partager

**Comment by niicojs** [comment]
that is the spirit and thanks for that really. I'm just saying we can do better, maybe some sparkling animated thingy?

**Comment by deathart** [comment]
Oui amélioration comme par exemple sur la droite du nombre de bonbon mettre une flêche vert le haut vert

**Comment by deathart** [comment]
J'ai envoyer un pull request par rapport au traduction dans celui-ci :s

**Comment by Epinikion** [comment]
as u can see i have a different version of this feature in my [pull request](https://github.com/nicoschmitt/necrobotvisualizer/pull/73)

the code is fine just modified it for the screen, to show the circle, just in case u wonder why it shows on 7/0 candys

necrobotvisualizerevolvepokemon

**Pull request closed without merging**
