### PR TITLE
[Feature] Secondary Sort For PokemonID

### PR DESCRIPTION
**Pull request by WORMSS**
When sorting by pokemon id, do a secondary sort by IV if the PokemonID is the same.

### CODE REVIEW

**Comment by WORMSS** [comment]
Unmerged?

**Comment by niicojs** [comment]
I did spend some time today to merge stuff I did on another project to this one, and this includes secondary sort, so it should do it.
You can check current master and tell me.

**Comment by WORMSS** [comment]
I am guessing a very quick overview of your code, it sorts CP before IV?

**Comment by niicojs** [comment]
true

**Comment by WORMSS** [comment]
Ok.. I'l have to revert that change for my personal version then.

**Pull request closed without merging**
