### PR TITLE
show how to use with necrobot

### PR DESCRIPTION
**Pull request by timelf123**

### CODE REVIEW

**Comment by niicojs** [comment]
I've just update both code and release. Could you please reinstall it?
It should work by default with latest bot source code without modiifiying it anymore.

**Comment by timelf123** [comment]
With latest sourcecode from master, I get

> "WebSocket connection to 'ws://localhost:14251/' failed: Error during WebSocket handhake: net::ERR_CONNECTION_RESET", source: necrobotvisualizer/app/scripts/app.js (14)

**Comment by niicojs** [comment]
Go into settings (small icon upper right) and change to wss://localhost:14251/

**Comment by timelf123** [comment]
Awesome, thanks for that

**Comment by niicojs** [comment]
Working fine?

**Comment by timelf123** [comment]
Yes

**Pull request closed without merging**
