### PR TITLE
Optimized all the images and tweaked the main UI

### PR DESCRIPTION
**Pull request by miracle091**

### CODE REVIEW

**Comment by miracle091** [comment]
@nicoschmitt this is the first pull for make it more "sweet" for the eyes, more things are coming in the next days

**Comment by niicojs** [comment]
do you have a screenshot please?

**Comment by miracle091** [comment]
sure, here is it http://imgur.com/a/8U35J

**Comment by Epinikion** [comment]
Dont get what exactly u did for the eycandy instead of the scrollbar and box-shadow for the toolbar. Every image that u commited is still the same as before.

The scrollbar is okay imo.

**Pull request merged**
