### PR TITLE
Update inventory.de.js

### PR DESCRIPTION
**Pull request by bin101**
add german translation

### CODE REVIEW

**Comment by niicojs** [comment]
There was an issue, it was not a key it was a lure module. Could you translate that also if you don't mind?

**Comment by bin101** [comment]
what should i translate?

**Comment by niicojs** [comment]
501, which was "Troy Disk" is actually "Lure Module"

**Comment by bin101** [comment]
yeah and in german it is "Lockmodul" ;)

**Comment by niicojs** [comment]
I'll update it, thanks

**Comment by niicojs** [comment]
or revert what you did :)

**Comment by bin101** [comment]
had i little typo:
1001: "Pokémon-Aufbewahung-Plus",

is actually
"Pokémon-Aufbewahrung-Plus"

**Comment by niicojs** [comment]
ok, fixed

**Pull request merged**
