### PR TITLE
IT translation (WIP)

### PR DESCRIPTION
**Pull request by aetherstrata**

### CODE REVIEW

**Comment by niicojs** [comment]
What do you mean by "WIP"? Do you want to wait before merge?

**Comment by aetherstrata** [comment]
Yes, pokemon.it.json is not fully translated...

**Comment by aetherstrata** [comment]
Tomorrow I'll finish it :smile:

**Comment by aetherstrata** [comment]
So, I reviewed the file and I can say that all the names are the same between italian and english.
Ready to merge!

**Pull request merged**
