### PR TITLE
Layers for markers and path. + the map moves with the player

### PR DESCRIPTION
**Pull request by nicdcs**

### CODE REVIEW

**Comment by niicojs** [comment]
Thanks. I've integrated most of your PR.
I've made "Follow Player" an option as I don't really like it doing it for me.

Next time, please do a PR for each functionnality (one for follow player, one for map options).

Thanks!!!!

**Comment by nicdcs** [comment]
I don't get why you then just copy the lines by hand, instead of letting me correct this PR (like removing the first commit, or even making the panning optional myself) :/

**Comment by niicojs** [comment]
Honestly it was for learning purposes. I'm new to leaflet so I wanted to redo it step by step to understand it. Sorry about that.
Thanks for the contribution.

**Comment by nicdcs** [comment]
It is easier to sync my fork with your upstream if you just merge my commits :smile:

I'm new to leaflet aswell, but I'm used to work with apis.

**Pull request closed without merging**
